### ISSUE TITLE
PHP Implode Paramets Backwards

### ISSUE THREAD

**Issue by M5F64rIqXCsyplvg9GK5** [mrbobdobolina/movie-night-stats#2]
Flip around php implode functions to be implode($needle, $array) so that it works in PHP 8!

**Comment by mrbobdobolina** [comment]
Best I can tell this is fixed on my local server.

**Comment by M5F64rIqXCsyplvg9GK5** [comment]
So I just learned about this before I submitted commit 7916f09 . If you put "Fixed #2" or anything in [this list](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), it will auto close an issue when that commit is merged into the main branch.

Not sure which way is the best way to manage issues, but I was curious to see how this worked.
